### ISSUE TITLE
Dialog Selection

### ISSUE THREAD

**Issue by nacyv** [jacktor-stan/battery-lab#8]
![Screenshot_20241120-133249_Battery Lab](https://github.com/user-attachments/assets/10aa8ac6-1220-4f49-a5ee-b662fd96156e)
checked image in dialog is not visible

**Comment by ardo-zapp** [comment]
I've noticed this before but there's no solution at the moment, thanks for letting me know.

**Comment by gryzzlaycutzy121** [comment]
What this bug?

**Comment by archanaberry** [comment]
Weh @jacktor-stan kalo dah di fix jangan lupa di close

**Comment by ardo-zapp** [comment]
Belum bisa di tutup sampai di uji coba pada **Android 13** kebawah

**Comment by ardo-zapp** [comment]
Bug fixed: https://github.com/jacktor-stan/battery-lab/commit/c42db8ae998cdc60fd69ff04f25f171aa057b921
